import{describe,it,expect}from'vitest';import{emptyResume}from'./resume';import{normalizeResume}from'./normalize';import{parseResume}from'./schema';import{migrateResume}from'./migrations';import{createId,isId}from'./id';
describe('Resume V1',()=>{
it('creates exact secure domain IDs',()=>{const ids=Array.from({length:50},()=>createId());expect(ids.every(isId)).toBe(true);expect(new Set(ids).size).toBe(ids.length)});
it('accepts valid Arabic and English resumes',()=>{expect(parseResume(emptyResume('ar')).locale).toBe('ar');expect(parseResume(emptyResume('en')).locale).toBe('en')});
it('rejects invalid section permutations',()=>{const r=emptyResume();r.sectionOrder=['summary','summary','education','skills','languages','certifications','projects','courses'];expect(()=>parseResume(r)).toThrow()});
it('rejects malformed IDs',()=>{const r=emptyResume();r.id='not-valid';expect(()=>parseResume(r)).toThrow()});
it('rejects javascript URLs',()=>{const r=emptyResume();r.personal.website='javascript:alert(1)';expect(()=>parseResume(r)).toThrow()});
it('allows angle brackets as plain text',()=>{const r=emptyResume();r.summary='<developer>';expect(parseResume(r).summary).toBe('<developer>')});
it('rejects control characters',()=>{const r=emptyResume();r.summary='ok\u0000bad';expect(()=>parseResume(r)).toThrow()});
it('rejects invalid experience range',()=>{const r=emptyResume();r.experience=[{id:createId(),role:'x',company:'y',location:'',start:'2026-12',end:'2026-01',current:false,description:''}];expect(()=>parseResume(r)).toThrow()});
it('accepts current experience without end date',()=>{const r=emptyResume();r.experience=[{id:createId(),role:'x',company:'y',location:'',start:'2026-01',end:'',current:true,description:''}];expect(parseResume(r).experience[0].current).toBe(true)});
it('v1 migration validates',()=>expect(migrateResume(emptyResume()).schemaVersion).toBe(1));
it('rejects future schema',()=>expect(()=>migrateResume({...emptyResume(),schemaVersion:2})).toThrow())
});
describe('resume normalization',()=>{it('cleans text, unsafe urls and duplicate skills',()=>{const r=emptyResume('ar');r.personal.fullName='  محمد   العقلة  ';r.personal.website='javascript:alert(1)';r.skills=[' React ','React','',' TypeScript '];const n=normalizeResume(r);expect(n.personal.fullName).toBe('محمد العقلة');expect(n.personal.website).toBe('');expect(n.skills).toEqual(['React','TypeScript'])});it('clears end date for current experience',()=>{const r=emptyResume();r.experience=[{id:r.id,role:'Dev',company:'MO',location:'',start:'2025-01',end:'2026-01',current:true,description:''}];expect(normalizeResume(r).experience[0].end).toBe('')})});

describe('coverage edge cases',()=>{it('validates basic resume fields',async()=>{const {validateResume}=await import('./resume');const r=emptyResume();expect(validateResume(r).valid).toBe(false);r.personal.fullName='Mohammed';r.personal.email='bad';expect(validateResume(r).errors).toContain('email');r.personal.email='m@example.com';expect(validateResume(r).valid).toBe(true)});it('normalizes https urls and all nested text',()=>{const r=emptyResume();r.personal.website='https://example.com';r.personal.linkedin='https://linkedin.com/in/test';r.languages=[{id:r.id,name:' Arabic ',level:' Native '}];r.certifications=[{id:r.id,name:' Cert ',issuer:' Issuer ',date:'2026-01',url:'https://example.com/c'}];r.projects=[{id:r.id,name:' Project ',role:' Lead ',date:'2026-01',description:' Desc ',url:'https://example.com/p'}];r.courses=[{id:r.id,name:' Course ',provider:' Provider ',date:'2026-01'}];const n=normalizeResume(r);expect(n.personal.website).toContain('https://example.com');expect(n.languages[0].name).toBe('Arabic');expect(n.certifications[0].name).toBe('Cert');expect(n.projects[0].description).toBe('Desc');expect(n.courses[0].provider).toBe('Provider')});it('rejects invalid education date range and unsafe nested urls',()=>{const r=emptyResume();r.education=[{id:r.id,degree:'x',field:'x',school:'x',location:'',start:'2026-02',end:'2025-01',description:''}];expect(()=>parseResume(r)).toThrow();const x=emptyResume();x.certifications=[{id:x.id,name:'x',issuer:'x',date:'',url:'http://unsafe.test'}];expect(()=>parseResume(x)).toThrow()})});
