import {useEffect,useState} from 'react';import Builder from './Builder';import Dashboard from './Dashboard';import Auth from './Auth';import Legal from './Legal';import{auth}from'./services/auth';
import{ArrowLeft,PlayCircle,Globe2,ShieldCheck,Zap,Users,FileText,Sparkles,Target,Download,Eye,WandSparkles,ChevronLeft,ChevronRight,LockKeyhole,Star,UserRound,Plus}from'lucide-react';
const templates=['كلاسيكي','احترافي','عصري','إبداعي','بسيط وأنيق'];
const faqs=['هل استخدام المنصة مجاني؟','هل القوالب متوافقة مع أنظمة ATS؟','هل يمكنني إنشاء السيرة باللغتين؟','هل يمكنني تعديل السيرة بعد التحميل؟','ما هي صيغ التصدير المتوفرة؟','هل بياناتي الشخصية آمنة؟'];
function Resume({accent=false}:{accent?:boolean}){return <div className={'resume '+(accent?'accent':'')}><div className="rhead"><div><b>أحمد محمد</b><small>مهندس برمجيات</small></div><div className="avatar">AM</div></div><h6>الملخص المهني</h6><p>مهندس برمجيات بخبرة في تطوير المنتجات الرقمية وبناء حلول عالية الجودة.</p><h6>الخبرات العملية</h6><div className="line w90"/><div className="line w70"/><div className="line w80"/><h6>التعليم</h6><div className="line w80"/><h6>المهارات</h6><div className="bars"><i/><i/><i/></div></div>}
export default function App(){const[locale,setLocale]=useState<'ar'|'en'>(()=>location.pathname.includes('/en')?'en':'ar');const[signedIn,setSignedIn]=useState(false);const[authReady,setAuthReady]=useState(false);useEffect(()=>{void auth.user().then(u=>{setSignedIn(!!u);setAuthReady(true)});return auth.onAuthStateChange(v=>{setSignedIn(v);setAuthReady(true)})},[]);const[open,setOpen]=useState<number|null>(null);const[view,setView]=useState<'home'|'dashboard'|'builder'|'login'|'signup'|'privacy'|'terms'>('home');const[resumeId,setResumeId]=useState<string|undefined>();if(view==='privacy'||view==='terms')return <Legal type={view} onBack={()=>setView('home')}/>;if(view==='login'||view==='signup')return <Auth mode={view} onBack={()=>setView('home')} onDone={()=>{setSignedIn(true);setView('dashboard')}}/>;if((view==='dashboard'||view==='builder')&&auth.isCloudConfigured()&&authReady&&!signedIn)return <Auth mode="login" onBack={()=>setView('home')} onDone={()=>{setSignedIn(true);setView('dashboard')}}/>;if(view==='builder')return <Builder id={resumeId} onBack={()=>setView('dashboard')}/>;if(view==='dashboard')return <Dashboard onHome={()=>setView('home')} open={(id)=>{setResumeId(id);setView('builder')}}/>;const toggleLocale=()=>{const next=locale==='ar'?'en':'ar';setLocale(next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';localStorage.setItem('mocv.locale',next)};return <main dir={locale==='ar'?'rtl':'ltr'} lang={locale}>
<header><a className="brand" href="#"><span>MO</span><b>MO CV</b></a><nav><a href="#features">الميزات</a><a href="#templates">القوالب</a><a href="#how">كيف يعمل؟</a><a href="#faq">الأسئلة الشائعة</a><a href="#contact">تواصل معنا</a></nav><div className="actions"><button className="lang" onClick={toggleLocale}><Globe2/> {locale==='ar'?'English':'العربية'}</button><button className="login" onClick={()=>setView('login')}>تسجيل الدخول</button><button className="primary" onClick={()=>setView('signup')}>ابدأ مجاناً</button></div></header>
<section className="hero"><div className="heroCopy"><div className="badge">🚀 منصة احترافية للسير الذاتية بالذكاء الاصطناعي</div><h1>اصنع سيرتك الذاتية<br/>الاحترافية <em>في دقائق</em></h1><p>صمم سيرتك الذاتية بالعربية والإنجليزية مع مساعد ذكي وقوالب احترافية متوافقة مع أنظمة ATS لفرص أفضل في سوق العمل.</p><div className="ctas"><button className="primary big" onClick={()=>setView('signup')}>ابدأ مجاناً الآن <ArrowLeft/></button><button className="secondary" onClick={()=>document.getElementById('how')?.scrollIntoView({behavior:'smooth'})}>شاهد كيف يعمل <PlayCircle/></button></div><div className="benefits"><span><Users/>احترافية عالمياً</span><span><ShieldCheck/>متوافقة مع ATS</span><span><Zap/>بالذكاء الاصطناعي</span><span><Globe2/>دعم عربي / إنجليزي</span></div></div>
<div className="heroVisual"><div className="paper back"><Resume/></div><div className="paper front"><Resume accent/></div><div className="languageCard"><b>✓ العربية</b><span>English</span></div><div className="toolCard"><span><WandSparkles/> تعديل بالذكاء الاصطناعي</span><span><Eye/> معاينة</span><span><Download/> تحميل PDF</span></div></div></section>
<section id="features" className="section"><h2>لماذا تختار MO CV؟</h2><p className="lead">نجمع بين الهندسة البرمجية المتقنة والذكاء الاصطناعي لنقدم لك أفضل تجربة لبناء مستقبلك المهني.</p><div className="features"><article><div className="icon pink"><Target/></div><h3>متوافقة مع أنظمة ATS</h3><p>قوالب مصممة لتحسين التوافق مع أنظمة الفرز الآلي للشركات.</p></article><article><div className="icon cyan"><FileText/></div><h3>قوالب احترافية ومتنوعة</h3><p>اختر من مجموعة واسعة من القوالب المصممة بعناية.</p></article><article><div className="icon purple"><Sparkles/></div><h3>مساعد ذكي بالذكاء الاصطناعي</h3><p>طوّر خبراتك وملخصك المهني بلغة قوية وطبيعية.</p></article><article><div className="icon blue"><Globe2/></div><h3>دعم ثنائي اللغة</h3><p>حرر سيرتك بالعربية والإنجليزية مع تجربة RTL وLTR.</p></article></div></section>
<section id="templates" className="section soft"><h2>قوالب احترافية تناسب جميع التخصصات</h2><p className="lead">اختر القالب الذي يعكس شخصيتك ومجالك المهني.</p><div className="templateRow"><button className="round"><ChevronRight/></button>{templates.map((t,i)=><article className={'template t'+i} key={t}><Resume accent={i===1}/><b>{t}</b></article>)}<button className="round"><ChevronLeft/></button></div></section>
<section id="how" className="section"><h2>كيف يعمل؟</h2><p className="lead">خطوات بسيطة للوصول إلى سيرة ذاتية احترافية في دقائق.</p><div className="steps">{[['1','أنشئ حسابك','تسجيل سريع ومجاني',UserRound],['2','اختر قالبك','من مجموعة قوالب احترافية',FileText],['3','أضف معلوماتك','بالعربية والإنجليزية',FileText],['4','حسّنها بالذكاء الاصطناعي','واحصل على اقتراحات احترافية',Sparkles]].map(([n,h,p,I]:any)=><article><i>{n}</i><I/><div><h3>{h}</h3><p>{p}</p></div></article>)}</div></section>
<section className="ai"><div className="chat"><div className="tabs">العربية　 English</div><p>حسّن هذا الوصف لوظيفة مهندس برمجيات...</p><div className="answer">قمت بتطوير وصيانة تطبيقات ويب عالية الأداء باستخدام تقنيات حديثة، مما ساهم في تحسين سرعة النظام وتجربة المستخدم.</div><div><button onClick={()=>setView(signedIn?'dashboard':'signup')}>إعادة التوليد</button><button className="primary" onClick={()=>setView(signedIn?'dashboard':'signup')}>✓ استخدام النص</button></div></div><div className="aiCopy"><h2>مساعد ذكي يعزز سيرتك الذاتية</h2><p>احصل على اقتراحات احترافية لصياغة خبراتك وملخصك المهني باستخدام الذكاء الاصطناعي، مع أمثلة عملية مصممة خصيصاً لمجالك الوظيفي.</p><button className="secondary" onClick={()=>setView(signedIn?'dashboard':'signup')}>جرّب المساعد الذكي الآن ✨</button></div><div className="bot">🤖</div></section>
<div className="trust"><span><LockKeyhole/> <b>بياناتك آمنة</b><small>نحمي خصوصيتك بأعلى المعايير</small></span><span><Users/> <b>مستخدمون حول العالم</b><small>من مختلف التخصصات</small></span><span><Star/> <b>أداة موثوقة</b><small>تجربة رقمية احترافية</small></span></div>
<section id="faq" className="section faq"><h2>الأسئلة الشائعة</h2><p className="lead">إجابات سريعة لأكثر الأسئلة شيوعاً.</p><div className="faqGrid">{faqs.map((q,i)=><button onClick={()=>setOpen(open===i?null:i)}><span>{q}{open===i&&<small> سيتم توضيح هذه الميزة بالتفصيل عند إطلاقها ضمن المنتج.</small>}</span><Plus/></button>)}</div></section>
<footer id="contact"><a className="brand"><span>MO</span><b>MO CV</b></a><p>منصة احترافية لبناء السير الذاتية بالذكاء الاصطناعي.</p><nav><a href="#features">الميزات</a>　<a href="#templates">القوالب</a>　<a href="#faq">الأسئلة الشائعة</a>　<a href="#contact">تواصل معنا</a>　<button className="footerLink" onClick={()=>setView('privacy')}>سياسة الخصوصية</button>　<button className="footerLink" onClick={()=>setView('terms')}>الشروط والأحكام</button></nav><small>© 2026 MO CV. جميع الحقوق محفوظة.</small></footer>
</main>}