import {useEffect,useState} from 'react';import Builder from './Builder';import Dashboard from './Dashboard';import Auth from './Auth';import Legal from './Legal';import{auth}from'./services/auth';
import{ArrowLeft,PlayCircle,Globe2,ShieldCheck,Zap,Users,FileText,Sparkles,Target,Download,Eye,WandSparkles,ChevronLeft,ChevronRight,LockKeyhole,Star,UserRound,Plus}from'lucide-react';
const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/mo-cv-images/${name}`;
const templates=[
 {name:'كلاسيكي',image:'04-template-classic.webp'},
 {name:'احترافي',image:'05-template-professional.webp'},
 {name:'عصري',image:'06-template-modern.webp'},
 {name:'إبداعي',image:'07-template-creative.webp'},
 {name:'بسيط وأنيق',image:'08-template-elegant.webp'}
];
const faqs=[['هل استخدام المنصة مجاني؟','يمكنك البدء وإنشاء سيرتك وتعديلها، وتظهر أي حدود للخدمات الاختيارية بوضوح داخل المنتج.'],['هل القوالب متوافقة مع أنظمة ATS؟','القوالب مصممة ببنية واضحة وقابلة للقراءة، ويتضمن المحرر فحص ATS ومطابقة كلمات الوصف الوظيفي.'],['هل يمكنني إنشاء السيرة باللغتين؟','نعم، يدعم المحرر العربية والإنجليزية واتجاهي RTL وLTR.'],['هل يمكنني تعديل السيرة بعد التحميل؟','نعم، تبقى السيرة قابلة للتعديل والحفظ وإعادة التصدير من لوحة التحكم.'],['ما هي صيغ التصدير المتوفرة؟','يتوفر تصدير PDF عبر معاينة الطباعة المحسنة لمقاس A4.'],['هل بياناتي الشخصية آمنة؟','عند تفعيل التخزين السحابي تُعزل بيانات كل مستخدم بصلاحيات قاعدة البيانات، ويمكن حذف الحساب وبياناته من لوحة التحكم.']];
function Resume({accent=false}:{accent?:boolean}){return <div className={'resume '+(accent?'accent':'')}><div className="rhead"><div><b>أحمد محمد</b><small>مهندس برمجيات</small></div><div className="avatar">AM</div></div><h6>الملخص المهني</h6><p>مهندس برمجيات بخبرة في تطوير المنتجات الرقمية وبناء حلول عالية الجودة.</p><h6>الخبرات العملية</h6><div className="line w90"/><div className="line w70"/><div className="line w80"/><h6>التعليم</h6><div className="line w80"/><h6>المهارات</h6><div className="bars"><i/><i/><i/></div></div>}
export default function App(){const[locale,setLocale]=useState<'ar'|'en'>(()=>{const saved=localStorage.getItem('mocv.locale');return saved==='en'||saved==='ar'?saved:'ar'});const[signedIn,setSignedIn]=useState(false);const[authReady,setAuthReady]=useState(false);useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr'},[locale]);useEffect(()=>{void auth.user().then(u=>{setSignedIn(!!u);setAuthReady(true)});return auth.onAuthStateChange(v=>{setSignedIn(v);setAuthReady(true)})},[]);const[open,setOpen]=useState<number|null>(null);const[templateOffset,setTemplateOffset]=useState(0);const[view,setView]=useState<'home'|'dashboard'|'builder'|'login'|'signup'|'privacy'|'terms'>('home');const[resumeId,setResumeId]=useState<string|undefined>();if(view==='privacy'||view==='terms')return <Legal type={view} onBack={()=>setView('home')}/>;if(view==='login'||view==='signup')return <Auth mode={view} onBack={()=>setView('home')} onDone={()=>{setSignedIn(true);setView('dashboard')}}/>;if((view==='dashboard'||view==='builder')&&auth.isCloudConfigured()&&authReady&&!signedIn)return <Auth mode="login" onBack={()=>setView('home')} onDone={()=>{setSignedIn(true);setView('dashboard')}}/>;if(view==='builder')return <Builder id={resumeId} onBack={()=>setView('dashboard')}/>;if(view==='dashboard')return <Dashboard onHome={()=>setView('home')} open={(id)=>{setResumeId(id);setView('builder')}}/>;const toggleLocale=()=>{const next=locale==='ar'?'en':'ar';setLocale(next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';localStorage.setItem('mocv.locale',next)};return <main dir={locale==='ar'?'rtl':'ltr'} lang={locale}>
<header><a className="brand" href="#"><span>MO</span><b>MO CV</b></a><nav><a href="#features">الميزات</a><a href="#templates">القوالب</a><a href="#how">كيف يعمل؟</a><a href="#faq">الأسئلة الشائعة</a><a href="#contact">تواصل معنا</a></nav><div className="actions"><button className="lang" onClick={toggleLocale}><Globe2/> {locale==='ar'?'English':'العربية'}</button><button className="login" onClick={()=>setView('login')}>تسجيل الدخول</button><button className="primary" onClick={()=>setView('signup')}>ابدأ مجاناً</button></div></header>
<section className="hero"><div className="heroCopy"><div className="badge">🚀 منصة احترافية للسير الذاتية بالذكاء الاصطناعي</div><h1>اصنع سيرتك الذاتية<br/>الاحترافية <em>في دقائق</em></h1><p>صمم سيرتك الذاتية بالعربية والإنجليزية مع مساعد ذكي وقوالب احترافية متوافقة مع أنظمة ATS لفرص أفضل في سوق العمل.</p><div className="ctas"><button className="primary big" onClick={()=>setView('signup')}>ابدأ مجاناً الآن <ArrowLeft/></button><button className="secondary" onClick={()=>document.getElementById('how')?.scrollIntoView({behavior:'smooth'})}>شاهد كيف يعمل <PlayCircle/></button></div><div className="benefits"><span><Users/>احترافية عالمياً</span><span><ShieldCheck/>متوافقة مع ATS</span><span><Zap/>بالذكاء الاصطناعي</span><span><Globe2/>دعم عربي / إنجليزي</span></div></div>
<div className="heroVisual"><div className="paper back imagePaper"><img src={asset('03-hero-cv-back.webp')} alt="نموذج سيرة ذاتية احترافي خلفي"/></div><div className="paper front imagePaper"><img src={asset('02-hero-cv-main.webp')} alt="نموذج سيرة ذاتية احترافي لمحمد منصور"/></div><div className="languageCard"><b>✓ العربية</b><span>English</span></div><div className="toolCard"><span><WandSparkles/> تعديل بالذكاء الاصطناعي</span><span><Eye/> معاينة</span><span><Download/> تحميل PDF</span></div></div></section>
<section id="features" className="section"><h2>لماذا تختار MO CV؟</h2><p className="lead">نجمع بين الهندسة البرمجية المتقنة والذكاء الاصطناعي لنقدم لك أفضل تجربة لبناء مستقبلك المهني.</p><div className="features"><article><div className="icon pink"><Target/></div><h3>متوافقة مع أنظمة ATS</h3><p>قوالب مصممة لتحسين التوافق مع أنظمة الفرز الآلي للشركات.</p></article><article><div className="icon cyan"><FileText/></div><h3>قوالب احترافية ومتنوعة</h3><p>اختر من مجموعة واسعة من القوالب المصممة بعناية.</p></article><article><div className="icon purple"><Sparkles/></div><h3>مساعد ذكي بالذكاء الاصطناعي</h3><p>طوّر خبراتك وملخصك المهني بلغة قوية وطبيعية.</p></article><article><div className="icon blue"><Globe2/></div><h3>دعم ثنائي اللغة</h3><p>حرر سيرتك بالعربية والإنجليزية مع تجربة RTL وLTR.</p></article></div></section>
<section id="templates" className="section soft"><h2>قوالب احترافية تناسب جميع التخصصات</h2><p className="lead">اختر القالب الذي يعكس شخصيتك ومجالك المهني.</p><div className="templateRow"><button className="round" aria-label="القالب السابق" onClick={()=>setTemplateOffset((templateOffset-1+templates.length)%templates.length)}><ChevronRight/></button>{templates.map((_,i)=>{const idx=(i+templateOffset)%templates.length,t=templates[idx];return <article className={'template t'+idx} key={t.name}><img className="templateImage" src={asset(t.image)} alt={`قالب ${t.name} للسيرة الذاتية`}/><b>{t.name}</b></article>})}<button className="round" aria-label="القالب التالي" onClick={()=>setTemplateOffset((templateOffset+1)%templates.length)}><ChevronLeft/></button></div></section>
<section id="how" className="section"><h2>كيف يعمل؟</h2><p className="lead">خطوات بسيطة للوصول إلى سيرة ذاتية احترافية في دقائق.</p><div className="steps">{[['1','أنشئ حسابك','تسجيل سريع ومجاني',UserRound],['2','اختر قالبك','من مجموعة قوالب احترافية',FileText],['3','أضف معلوماتك','بالعربية والإنجليزية',FileText],['4','حسّنها بالذكاء الاصطناعي','واحصل على اقتراحات احترافية',Sparkles]].map(([n,h,p,I]:any)=><article><i>{n}</i><I/><div><h3>{h}</h3><p>{p}</p></div></article>)}</div></section>
<section className="ai"><div className="aiDemo"><img src={asset('10-ai-demo.webp')} alt="واجهة المساعد الذكي لتحسين نص السيرة الذاتية"/></div><div className="aiCopy"><h2>مساعد ذكي يعزز سيرتك الذاتية</h2><p>احصل على اقتراحات احترافية لصياغة خبراتك وملخصك المهني باستخدام الذكاء الاصطناعي، مع أمثلة عملية مصممة خصيصاً لمجالك الوظيفي.</p><button className="secondary" onClick={()=>setView(signedIn?'dashboard':'signup')}>جرّب المساعد الذكي الآن ✨</button></div><div className="botImage"><img src={asset('09-ai-assistant.webp')} alt="مساعد MO CV الذكي"/></div></section>
<div className="trust"><span><LockKeyhole/> <b>بياناتك آمنة</b><small>نحمي خصوصيتك بأعلى المعايير</small></span><span><Users/> <b>مستخدمون حول العالم</b><small>من مختلف التخصصات</small></span><span><Star/> <b>أداة موثوقة</b><small>تجربة رقمية احترافية</small></span></div>
<section id="faq" className="section faq"><h2>الأسئلة الشائعة</h2><p className="lead">إجابات سريعة لأكثر الأسئلة شيوعاً.</p><div className="faqGrid">{faqs.map(([q,a],i)=><button key={q} aria-expanded={open===i} onClick={()=>setOpen(open===i?null:i)}><span>{q}{open===i&&<small>{a}</small>}</span><Plus className={open===i?'rotated':''}/></button>)}</div></section>
<footer id="contact"><a className="brand" href="#"><span>MO</span><b>MO CV</b></a><p>منصة احترافية لبناء السير الذاتية بالذكاء الاصطناعي.</p><nav><a href="#features">الميزات</a>　<a href="#templates">القوالب</a>　<a href="#faq">الأسئلة الشائعة</a>　<a href="#contact">تواصل معنا</a>　<button className="footerLink" onClick={()=>setView('privacy')}>سياسة الخصوصية</button>　<button className="footerLink" onClick={()=>setView('terms')}>الشروط والأحكام</button></nav><small>© 2026 MO CV. جميع الحقوق محفوظة.</small><div className="socials" aria-label="روابط التواصل"><a href="mailto:contact@mocv.app" aria-label="البريد الإلكتروني">✉</a><a href="#contact" aria-label="LinkedIn">in</a><a href="#contact" aria-label="X">𝕏</a></div></footer>
</main>}