import{useEffect,useState}from'react';import{FilePlus2,Pencil,Trash2,Copy,Edit3}from'lucide-react';import{repo}from'./domain/repository';import{emptyResume,type ResumeV1}from'./domain/resume';import{cloudRepo,type CloudResume}from'./services/cloudRepository';import{auth}from'./services/auth';import type{UiLocale}from'./i18n';
export default function Dashboard({open,onHome,locale}:{open:(id?:string)=>void;onHome:()=>void;locale:UiLocale}){
 const en=locale==='en';const tr=(ar:string,enText:string)=>en?enText:ar;
 const[items,setItems]=useState<ResumeV1[]>(()=>repo.all());const[cloud,setCloud]=useState<CloudResume[]>([]);const[choosingSaved,setChoosingSaved]=useState(false);const[error,setError]=useState('');const configured=cloudRepo.configured();
 const message=(_e:unknown,ar:string,enText:string)=>tr(ar,enText);
 const displayTitle=(title:string)=>{const t=(title||'').trim();if(en&&(t==='سيرتي الذاتية'||t==='سيرة ذاتية جديدة'))return 'My Resume';if(!en&&(t==='My Resume'||t==='New Resume'))return 'سيرتي الذاتية';return title};
 const dateText=(value:unknown)=>{const d=new Date(typeof value==='string'||typeof value==='number'?value:Date.now());return Number.isNaN(d.getTime())?tr('تاريخ غير متاح','Date unavailable'):d.toLocaleString(en?'en-US':'ar-JO')};
 async function load(){if(!configured){setItems(repo.all());return}try{const x=await cloudRepo.all();setCloud(x);setItems(x.map(v=>v.resume));setError('')}catch(e){setError(message(e,'تعذر تحميل السير السحابية','Could not load cloud resumes'))}}
 useEffect(()=>{void load()},[]);
 async function create(){const resumeLocale=en?'en':'ar';if(configured){try{const x=await cloudRepo.create(emptyResume(resumeLocale));open(x.resume.id)}catch(e){setError(message(e,'تعذر الإنشاء','Could not create resume'))}}else{const r=repo.create(resumeLocale);open(r.id)}}
 async function remove(id:string){if(!confirm(tr('حذف السيرة؟','Delete this resume?')))return;try{if(configured)await cloudRepo.remove(id);else repo.remove(id);await load()}catch(e){setError(message(e,'تعذر حذف السيرة','Could not delete resume'))}}
 async function duplicate(id:string){const suffix=en?' — Copy':' — نسخة';try{if(configured)await cloudRepo.duplicate(id,suffix);else repo.duplicate(id,suffix);await load()}catch(e){setError(message(e,'تعذر نسخ السيرة','Could not duplicate resume'))}}
 async function rename(r:ResumeV1){const n=prompt(tr('اسم السيرة','Resume name'),displayTitle(r.title));if(!n)return;try{if(configured){const x=cloud.find(v=>v.resume.id===r.id);if(!x)throw new Error(tr('تعذر العثور على السيرة','Could not find resume'));await cloudRepo.rename(r.id,n,x.writeVersion)}else repo.rename(r.id,n);await load()}catch(e){setError(message(e,'تعذر إعادة التسمية','Could not rename resume'))}}
 return <div className="dashboard" dir={en?'ltr':'rtl'}><header><b>MO CV</b><div><button onClick={onHome}>{tr('الرئيسية','Home')}</button><button onClick={async()=>{await auth.signOut();onHome()}}>{tr('تسجيل الخروج','Sign Out')}</button><button onClick={async()=>{if(!confirm(tr('حذف الحساب نهائياً وجميع السير الذاتية؟ لا يمكن التراجع.','Permanently delete the account and all resumes? This cannot be undone.')))return;try{await auth.deleteAccount();onHome()}catch(e){setError(message(e,'تعذر حذف الحساب','Could not delete account'))}}}>{tr('حذف الحساب','Delete Account')}</button></div></header><div className="dashHead"><div><h1>{tr('سيرك الذاتية','Your Resumes')}</h1><p>{configured?tr('محفوظة بأمان في حسابك السحابي.','Securely saved in your cloud account.'):tr('وضع محلي — اربط Supabase للحفظ السحابي.','Local mode — connect Supabase for cloud saving.')}</p>{error&&<small className="formError" role="status" aria-live="polite">{error}</small>}</div><div className="dashboardPrimaryActions"><button className="primary" onClick={create}><FilePlus2/> {tr('إنشاء سيرة جديدة','Create New Resume')}</button>{items.length>0&&<button className="secondary savedResumeCta" onClick={()=>setChoosingSaved(v=>!v)}><Pencil/> {tr('اختر سيرة محفوظة للتعديل','Choose a Saved Resume to Edit')}</button>}</div></div>{choosingSaved&&items.length>0&&<section className="savedResumePicker" aria-label={tr('اختر السيرة التي تريد تعديلها','Choose the resume you want to edit')}><h2>{tr('أي سيرة تريد تعديلها؟','Which resume do you want to edit?')}</h2><div>{items.map(r=><button key={r.id} type="button" onClick={()=>open(r.id)}><Pencil/><span><b>{displayTitle(r.title)}</b><small>{r.personal.fullName||tr('بدون اسم','No name')}{r.personal.jobTitle?' — '+r.personal.jobTitle:''}</small></span></button>)}</div></section>}<div className="resumeGrid">{items.length?items.map(r=><article key={r.id}><div className="miniCv" dir={r.locale==='ar'?'rtl':'ltr'} lang={r.locale}><span className="resumeLangBadge">{r.locale==='ar'?tr('لغة السيرة: العربية','Resume: Arabic'):tr('لغة السيرة: الإنجليزية','Resume: English')}</span><b>{r.personal.fullName||tr('سيرة ذاتية جديدة','New Resume')}</b><span>{r.personal.jobTitle}</span></div><h3>{displayTitle(r.title)}</h3><small>{dateText(r.updatedAt)}</small><div className="resumeActions"><button onClick={()=>open(r.id)}><Pencil/> {tr('تعديل','Edit')}</button><button onClick={()=>void duplicate(r.id)}><Copy/> {tr('نسخ','Duplicate')}</button><button onClick={()=>void rename(r)}><Edit3/> {tr('تسمية','Rename')}</button><button onClick={()=>void remove(r.id)}><Trash2/> {tr('حذف','Delete')}</button></div></article>):<div className="empty"><FilePlus2/><h2>{tr('ابدأ سيرتك الأولى','Create Your First Resume')}</h2><button className="primary" onClick={create}>{tr('إنشاء الآن','Create Now')}</button></div>}</div></div>
}