type Locale='ar'|'en';
export default function Legal({type,locale,onBack}:{type:'privacy'|'terms';locale:Locale;onBack:()=>void}){
 const ar=locale==='ar',t=(a:string,e:string)=>ar?a:e,privacy=type==='privacy';
 const privacySections=[
  ['البيانات التي نعالجها','Data We Process','نعالج بيانات الحساب ومحتوى السيرة الذاتية لتقديم وظائف MO CV، بما في ذلك الحفظ والمعاينة والتصدير والفحص الذي يطلبه المستخدم. لا تضع كلمات مرور أو أسراراً أو معلومات لا يلزم وجودها في السيرة.','We process account data and resume content to provide MO CV features, including saving, previewing, exporting, and requested safety checks. Do not place passwords, secrets, or unnecessary sensitive information in a resume.'],
  ['فحص المحتوى والأمان','Content & Safety Checks','قد تُفحص النصوص قبل التصدير لاكتشاف المحتوى المسيء أو البذيء أو الضار أو غير الملائم للاستخدام المهني. عند عدم اكتمال فحص الأمان يُمنع التصدير بدلاً من تجاوز الفحص.','Resume text may be checked before export for abusive, obscene, harmful, or professionally unsuitable content. If the required safety check cannot complete, export is blocked rather than bypassed.'],
  ['الملفات والصور','Files & Images','لا تتوفر حالياً ميزة رفع ملفات عامة داخل منشئ السيرة. عند إضافة أي رفع مستقبلاً يجب تطبيق التحقق من النوع والحجم ومؤشرات البرمجيات الضارة قبل المعالجة.','The resume builder currently does not provide general file uploads. Any future upload feature must validate file type, size, and malware indicators before processing.'],
  ['الاستخدام والحماية','Access & Protection','تُطبق صلاحيات وصول على مستوى المستخدم عند تفعيل قاعدة البيانات السحابية. قد تُسجل أحداث محدودة مرتبطة بمخالفات المحتوى لأغراض منع إساءة الاستخدام وتطبيق قواعد الخدمة.','User-level access controls protect cloud resume data. Limited moderation events may be recorded to prevent abuse and enforce service rules.'],
  ['الحذف','Deletion','يستطيع المستخدم حذف حسابه وبياناته من لوحة التحكم بعد تأكيد صريح وفق آلية الخدمة وقواعد الاحتفاظ المطبقة.','Users can request permanent account and resume deletion from the dashboard after explicit confirmation, subject to the service retention rules.']
 ];
 const termsSections=[
  ['الخدمة','Service','MO CV أداة لإنشاء السير الذاتية ولا تضمن الحصول على وظيفة أو اجتياز أنظمة التوظيف أو ATS.','MO CV is a resume-building tool. It does not guarantee employment, recruitment outcomes, or passage through an ATS.'],
  ['مسؤولية المحتوى','Content Responsibility','المستخدم مسؤول عن دقة وقانونية وملاءمة كل نص أو معلومة يدخلها وعن امتلاكه الحق في استخدامها. يمنع استخدام الخدمة للإساءة أو الإهانة أو المحتوى البذيء أو الفاحش أو الضار أو غير القانوني.','You are responsible for the accuracy, legality, suitability, and rights to all content you enter. Abusive, insulting, obscene, harmful, or unlawful use is prohibited.'],
  ['شرط التصدير','Export Requirements','لا يتم تصدير السيرة النهائية قبل مراجعة المحتوى، نجاح فحص الأمان المطلوب، وموافقة المستخدم الصريحة على إقرار المسؤولية. تعطل الفحص لا يعني السماح بالتصدير.','Final export requires content review, a successful required safety check, and explicit acceptance of the responsibility acknowledgement. A failed or unavailable check does not permit export.'],
  ['المخالفات','Violations','يمكن منع إنشاء أو تصدير السيرة عند اكتشاف مخالفة. قد تُسجل المخالفة، وقد تؤدي المخالفات المتكررة أو الجسيمة إلى تعليق استخدام الخدمة.','A detected violation can block export and may be recorded. Repeated or severe violations may suspend access to the affected service.'],
  ['جودة السيرة','Resume Quality','تهدف الخدمة إلى إخراج سيرة مهنية بالعربية أو الإنجليزية مع RTL/LTR صحيح، وأقسام واضحة، ومعاينة وطباعة دون قص أو تداخل أو صفحات فارغة غير مقصودة. يبقى على المستخدم مراجعة النسخة النهائية قبل استخدامها.','The service is designed to produce professional Arabic or English resumes with correct RTL/LTR direction, clear sections, and print output without unintended clipping, overlap, or blank pages. You must review the final document before use.'],
  ['الذكاء الاصطناعي','Artificial Intelligence','اقتراحات الذكاء الاصطناعي تحتاج مراجعة المستخدم قبل اعتمادها ولا تُطبق تلقائياً دون موافقته.','AI suggestions require user review before adoption and are not automatically accepted on your behalf.'],
  ['الإبلاغ عن مشكلة','Issue Reporting','يمكن للمستخدم الإبلاغ عن مشكلة في محتوى السيرة أو تنسيقها أو اللغة أو PDF أو ATS من أداة الإبلاغ بجانب المعاينة.','You can report content, formatting, language, PDF, or ATS issues from the reporting control beside the resume preview.']
 ];
 const sections=privacy?privacySections:termsSections;
 return <main className="legal" dir={ar?'rtl':'ltr'} lang={locale}><button onClick={onBack}>{t('← الرئيسية','← Home')}</button><h1>{privacy?t('سياسة الخصوصية','Privacy Policy'):t('الشروط والأحكام','Terms & Conditions')}</h1><p>{t('آخر تحديث: سبتمبر 2026','Last updated: September 2026')}</p>{sections.map(([ah,eh,ap,ep])=><section key={eh}><h2>{t(ah,eh)}</h2><p>{t(ap,ep)}</p></section>)}</main>
}